# Generated by Django 5.1 on 2024-08-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='last_reminded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='refill_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
