# Generated by Django 4.2 on 2024-12-15 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='emergency_contact',
        ),
    ]
