# Generated by Django 5.1 on 2024-09-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='synthesized_audio',
            field=models.FileField(blank=True, null=True, upload_to='synthesized_audio/'),
        ),
    ]
