# Generated by Django 4.2 on 2024-12-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reminder_foodreminder_drugreminder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='reminder_time',
            new_name='time',
        ),
    ]
