# Generated by Django 5.1 on 2024-09-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_audio_ai_response_audio_synthesized_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
    ]
