# Generated by Django 4.2 on 2024-12-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_title_reminder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(),
        ),
    ]
