# Generated by Django 5.1 on 2024-11-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_healthsyncscore_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthsyncscore',
            name='date',
            field=models.DateField(),
        ),
    ]
