include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

  exclude:
    - '**/*.g.dart'      
    - '**/*.freezed.dart' 
    - '**/*.config.dart' 
    - '**/*.gen.dart' 

  errors:
    missing_required_param: error
    missing_return: error
    invalid_assignment: warning
    invalid_annotation_target: ignore
    void_checks: ignore

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
