name: ellipsis_care

description: "An AI health assistant that can help keep track of people's health, and provide suggestions on lifestyle habits based on health conditions, and also provide basic diagnostics."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dev: ^1.0.0

  get_it: ^8.0.2
  go_router: ^14.2.7
  flutter_screenutil: ^5.9.3

  uuid: ^4.5.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.4

  dio: ^5.7.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  firebase_core: ^3.4.1
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  record: ^5.1.2
  awesome_notifications: ^0.10.0
  flutter_contacts: ^1.1.9+2
  speech_to_text: ^7.0.0
  table_calendar: ^3.1.2
  dotted_border: ^2.1.0
  pulsator: ^1.0.0+2
  intl: ^0.19.0
  mocktail: ^1.0.4
  community_charts_flutter: ^1.0.4
  image_picker: ^1.1.2
  audioplayers: ^6.1.0
  fpdart: ^1.1.1
  audio_service: ^0.18.15
  logman: ^0.0.21
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  pin_code_text_field: ^1.8.0
  talker_flutter: ^4.5.5
  talker_dio_logger: ^4.5.5
  talker_bloc_logger: ^4.5.5
  toastification: ^2.3.0
  sentry_flutter: ^8.12.0
  permission_handler: ^11.3.1
  flutter_secure_storage: ^9.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  flutter_flavorizr: ^2.2.3
  flutter_gen_runner: ^5.8.0

flutter_gen:
  output: lib/config/gen/

  assets:
    outputs:
      class_name: AppAssets
      package_parameter_enabled: false
      directory_path_enabled: true

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/authentication/
    - assets/icons/home/nav_bar/
    - assets/icons/home/actions/
    - assets/icons/dashboard/
    - assets/icons/reminder/
    - assets/icons/settings/
    - assets/icons/sos/
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
          
    - family: Colfax
      fonts:
        - asset: assets/fonts/colfax/Colfax-Regular.otf
        - asset: assets/fonts/colfax/Colfax-Bold.otf
          weight: 700

    - family: Visby Round CF
      fonts:
        - asset: assets/fonts/visby_round/VisbyRoundCF-Regular.otf
        - asset: assets/fonts/visby_round/VisbyRoundCF-Bold.otf
          weight: 700
      
flavorizr:
  ide: "vscode"

  app:
    android:
      flavorDimensions: "flavor-type"

  flavors:
    dev:
      app:
        name: "Ellipsis Care Dev"
      android:
        applicationId: "com.ellipsis.ellipsis_care.dev"
        icon: "assets/dev/app-logo-dev.png"
      ios:
        bundleId: "com.ellipsis.ellipsisCare.dev"
        icon: "assets/dev/app-logo-dev.png"
            
    prod:
      app:
        name: "Ellipsis Care"
      android:
        applicationId: "com.ellipsis.ellipsis_care"
        icon: "assets/prod/app-logo.png"
      ios:
        bundleId: "com.ellipsis.ellipsisCare"
        icon: "assets/prod/app-logo.png"
  