// Mocks generated by Mockito 5.4.5 from annotations
// in ellipsis_care/test/unit_test/repository/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ellipsis_care/core/api/exceptions/exceptions.dart' as _i6;
import 'package:ellipsis_care/core/api/response/api_response.dart' as _i5;
import 'package:ellipsis_care/src/features/authentication/data/auth_repository.dart'
    as _i2;
import 'package:ellipsis_care/src/features/authentication/models/signin/signin_response.dart'
    as _i9;
import 'package:ellipsis_care/src/features/authentication/models/signup/signup_response.dart'
    as _i8;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepository extends _i1.Mock
    implements _i2.AuthenticationRepository {
  MockAuthenticationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.ApiResponse<void>, _i6.AppExceptions>> userExists(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #userExists,
          [email],
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.ApiResponse<void>, _i6.AppExceptions>>.value(
            _i7.dummyValue<
                _i4.Either<_i5.ApiResponse<void>, _i6.AppExceptions>>(
          this,
          Invocation.method(
            #userExists,
            [email],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.ApiResponse<void>, _i6.AppExceptions>>);

  @override
  _i3.Future<
      _i4.Either<_i5.ApiResponse<_i8.SignupResponseNormal>,
          _i6.AppExceptions>> signUp(Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [payload],
        ),
        returnValue: _i3.Future<
            _i4.Either<_i5.ApiResponse<_i8.SignupResponseNormal>,
                _i6.AppExceptions>>.value(_i7.dummyValue<
            _i4.Either<_i5.ApiResponse<_i8.SignupResponseNormal>,
                _i6.AppExceptions>>(
          this,
          Invocation.method(
            #signUp,
            [payload],
          ),
        )),
      ) as _i3.Future<
          _i4.Either<_i5.ApiResponse<_i8.SignupResponseNormal>,
              _i6.AppExceptions>>);

  @override
  _i3.Future<_i4.Either<_i5.ApiResponse<_i9.SigninResponse>, _i6.AppExceptions>>
      signIn(Map<String, dynamic>? payload) => (super.noSuchMethod(
            Invocation.method(
              #signIn,
              [payload],
            ),
            returnValue: _i3.Future<
                _i4.Either<_i5.ApiResponse<_i9.SigninResponse>,
                    _i6.AppExceptions>>.value(_i7.dummyValue<
                _i4.Either<_i5.ApiResponse<_i9.SigninResponse>,
                    _i6.AppExceptions>>(
              this,
              Invocation.method(
                #signIn,
                [payload],
              ),
            )),
          ) as _i3.Future<
              _i4
              .Either<_i5.ApiResponse<_i9.SigninResponse>, _i6.AppExceptions>>);

  @override
  _i3.Future<_i4.Either<_i5.ApiResponse<void>, _i6.AppExceptions>> verifyEmail(
          Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [payload],
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.ApiResponse<void>, _i6.AppExceptions>>.value(
            _i7.dummyValue<
                _i4.Either<_i5.ApiResponse<void>, _i6.AppExceptions>>(
          this,
          Invocation.method(
            #verifyEmail,
            [payload],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.ApiResponse<void>, _i6.AppExceptions>>);

  @override
  _i3.Future<
      _i4.Either<_i5.ApiResponse<String>, _i6.AppExceptions>> forgotPassword(
          Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [payload],
        ),
        returnValue: _i3.Future<
                _i4.Either<_i5.ApiResponse<String>, _i6.AppExceptions>>.value(
            _i7.dummyValue<
                _i4.Either<_i5.ApiResponse<String>, _i6.AppExceptions>>(
          this,
          Invocation.method(
            #forgotPassword,
            [payload],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.ApiResponse<String>, _i6.AppExceptions>>);

  @override
  _i3.Future<
      _i4.Either<_i5.ApiResponse<_i8.SignupWithGoogleResponse>,
          _i6.AppExceptions>> signUpWithGoogle(String? idToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithGoogle,
          [idToken],
        ),
        returnValue: _i3.Future<
            _i4.Either<_i5.ApiResponse<_i8.SignupWithGoogleResponse>,
                _i6.AppExceptions>>.value(_i7.dummyValue<
            _i4.Either<_i5.ApiResponse<_i8.SignupWithGoogleResponse>,
                _i6.AppExceptions>>(
          this,
          Invocation.method(
            #signUpWithGoogle,
            [idToken],
          ),
        )),
      ) as _i3.Future<
          _i4.Either<_i5.ApiResponse<_i8.SignupWithGoogleResponse>,
              _i6.AppExceptions>>);
}
