// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk4ou0g-2D1MVCiVlrSgJWCZliYp3EH24',
    appId: '1:271967696940:android:ca82ce2900a9b5a79e7989',
    messagingSenderId: '271967696940',
    projectId: 'ellipsis-care-dev-5028b',
    storageBucket: 'ellipsis-care-dev-5028b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSlGyWtRL26osFfK3fohWTlf0yF48p3X8',
    appId: '1:271967696940:ios:c0e4d2ee5116f53a9e7989',
    messagingSenderId: '271967696940',
    projectId: 'ellipsis-care-dev-5028b',
    storageBucket: 'ellipsis-care-dev-5028b.firebasestorage.app',
    iosClientId: '271967696940-l7a7jc8p0enb0dl248o122a2n3k2d9h5.apps.googleusercontent.com',
    iosBundleId: 'com.ellipsis.ellipsisCare.dev',
  );

}