// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjmzxLUzNVr8UyR5BsOWfaGnxi4DqS8T4',
    appId: '1:1097324899248:web:29bc45ef6dffc3edbac475',
    messagingSenderId: '1097324899248',
    projectId: 'ellipsis-care-d8842',
    authDomain: 'ellipsis-care-d8842.firebaseapp.com',
    storageBucket: 'ellipsis-care-d8842.appspot.com',
    measurementId: 'G-8NCN0265KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAswmEfqzlRjB0-nSM-q4CZzZY3dUqzzb4',
    appId: '1:1097324899248:android:5ea97dbaf8babe71bac475',
    messagingSenderId: '1097324899248',
    projectId: 'ellipsis-care-d8842',
    storageBucket: 'ellipsis-care-d8842.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUYOmeEJvQJgQtU84XakLs3lf3V3bmebA',
    appId: '1:1097324899248:ios:f1212d8d2e4496bebac475',
    messagingSenderId: '1097324899248',
    projectId: 'ellipsis-care-d8842',
    storageBucket: 'ellipsis-care-d8842.appspot.com',
    androidClientId: '1097324899248-4cjc1thahg3m93g9grhks7afvkpon4pc.apps.googleusercontent.com',
    iosClientId: '1097324899248-gliehr0unf41i1doulqpjn55k7qhu266.apps.googleusercontent.com',
    iosBundleId: 'com.ellipsis.ellipsiscare',
  );

}